# Generated by Django 4.2.4 on 2023-10-04 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ridak', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registred',
        ),
    ]
